/* Automatically generated by './build/bin/build-entry.js' */

import Timedate from '../packages/timedate/index.js';
import Loading from '../packages/loading/index.js';
import Message from '../packages/message/index.js';
import InfiniteScroll from '../packages/Infinite-scroll/index.js';
import MessageBox from '../packages/message-box/index.js';
import DcTable from '../packages/dcTable/index.js';
import Scrollbar from '../packages/scrollbar/index.js';
import Row from '../packages/row/index.js';
import Backtop from '../packages/backtop/index.js';
import DctableMain from '../packages/dcTable-main/index.js';
import SearchContainer from '../packages/search-container/index.js';
import DcForm from '../packages/dcForm/index.js';
import DcButton from '../packages/dcButton/index.js';
import DividePanel from '../packages/divide-panel/index.js';
import PageSelect from '../packages/page-select/index.js';
import DcCard from '../packages/dcCard/index.js';
import DcCheckbox from '../packages/dcCheckbox/index.js';
import DcCheckboxGroup from '../packages/dcCheckboxGroup/index.js';
import DcInput from '../packages/dcInput/index.js';
import EditText from '../packages/edit-text/index.js';
import SmallCard from '../packages/small-card/index.js';
import DcTooltip from '../packages/dcTooltip/index.js';
import IpSwitch from '../packages/ip-switch/index.js';
import DcRadio from '../packages/dcRadio/index.js';
import DcCascader from '../packages/dcCascader/index.js';
import DcSwitch from '../packages/dcSwitch/index.js';
import DcUpload from '../packages/dcUpload/index.js';
import DcSelect from '../packages/dcSelect/index.js';
import DcTransfer from '../packages/dcTransfer/index.js';
import DcProgress from '../packages/dcProgress/index.js';
import DcPagination from '../packages/dcPagination/index.js';
import DcTree from '../packages/dcTree/index.js';
import DcDescriptions from '../packages/dcDescriptions/index.js';
import DcAlert from '../packages/dcAlert/index.js';
import DcMenu from '../packages/dcMenu/index.js';
import Tabs from '../packages/tabs/index.js';
import TabPane from '../packages/tab-pane/index.js';
import DcBreadcrumb from '../packages/dcBreadcrumb/index.js';
import DcBreadcrumbItem from '../packages/dcBreadcrumbItem/index.js';
import DcDropdown from '../packages/dcDropdown/index.js';
import DcDialog from '../packages/dcDialog/index.js';
import DcPopover from '../packages/dcPopover/index.js';
import DcCollapse from '../packages/dcCollapse/index.js';
import DcCollapseItem from '../packages/dcCollapseItem/index.js';
import DcTimeline from '../packages/dcTimeline/index.js';
import DcDivider from '../packages/dcDivider/index.js';
import DcDrawer from '../packages/dcDrawer/index.js';
import DcTag from '../packages/dcTag/index.js';
import DcCol from '../packages/dcCol/index.js';
import DcContainer from '../packages/dcContainer/index.js';
import DcHeader from '../packages/dcHeader/index.js';
import DcMain from '../packages/dcMain/index.js';
import DcAside from '../packages/dcAside/index.js';
import DcFooter from '../packages/dcFooter/index.js';
import DcEmpty from '../packages/dcEmpty/index.js';
import DcPopconfirm from '../packages/dcPopconfirm/index.js';
import DcRow from '../packages/dcRow/index.js';
import DcImage from '../packages/dcImage/index.js';
import locale from 'element-ui/src/locale';
import CollapseTransition from 'element-ui/src/transitions/collapse-transition';

const components = [
  Timedate,
  DcTable,
  Scrollbar,
  Row,
  Backtop,
  DctableMain,
  SearchContainer,
  DcForm,
  DcButton,
  DividePanel,
  PageSelect,
  DcCard,
  DcCheckbox,
  DcCheckboxGroup,
  DcInput,
  EditText,
  SmallCard,
  DcTooltip,
  IpSwitch,
  DcRadio,
  DcCascader,
  DcSwitch,
  DcUpload,
  DcSelect,
  DcTransfer,
  DcProgress,
  DcPagination,
  DcTree,
  DcDescriptions,
  DcAlert,
  DcMenu,
  Tabs,
  TabPane,
  DcBreadcrumb,
  DcBreadcrumbItem,
  DcDropdown,
  DcDialog,
  DcPopover,
  DcCollapse,
  DcCollapseItem,
  DcTimeline,
  DcDivider,
  DcDrawer,
  DcTag,
  DcCol,
  DcContainer,
  DcHeader,
  DcMain,
  DcAside,
  DcFooter,
  DcEmpty,
  DcPopconfirm,
  DcRow,
  DcImage,
  CollapseTransition
];

const install = function(Vue, opts = {}) {
  locale.use(opts.locale);
  locale.i18n(opts.i18n);

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.use(InfiniteScroll);
  Vue.use(Loading.directive);

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };

  Vue.prototype.$loading = Loading.service;
  Vue.prototype.$msgbox = MessageBox;
  Vue.prototype.$alert = MessageBox.alert;
  Vue.prototype.$confirm = MessageBox.confirm;
  Vue.prototype.$prompt = MessageBox.prompt;
  Vue.prototype.$notify = Notification;
  Vue.prototype.$message = Message;

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.2',
  locale: locale.use,
  i18n: locale.i18n,
  install,
  CollapseTransition,
  Loading,
  Timedate,
  Message,
  InfiniteScroll,
  MessageBox,
  DcTable,
  Scrollbar,
  Row,
  Backtop,
  DctableMain,
  SearchContainer,
  DcForm,
  DcButton,
  DividePanel,
  PageSelect,
  DcCard,
  DcCheckbox,
  DcCheckboxGroup,
  DcInput,
  EditText,
  SmallCard,
  DcTooltip,
  IpSwitch,
  DcRadio,
  DcCascader,
  DcSwitch,
  DcUpload,
  DcSelect,
  DcTransfer,
  DcProgress,
  DcPagination,
  DcTree,
  DcDescriptions,
  DcAlert,
  DcMenu,
  Tabs,
  TabPane,
  DcBreadcrumb,
  DcBreadcrumbItem,
  DcDropdown,
  DcDialog,
  DcPopover,
  DcCollapse,
  DcCollapseItem,
  DcTimeline,
  DcDivider,
  DcDrawer,
  DcTag,
  DcCol,
  DcContainer,
  DcHeader,
  DcMain,
  DcAside,
  DcFooter,
  DcEmpty,
  DcPopconfirm,
  DcRow,
  DcImage
};
